

keywords = {
    "Clinical Status": [
        r"stable",
        "risk",
        "VS",
        "VSS",
        "irregular",
        "GCS",
        r"oriented x ?\d",
    ],
    "Mobility": [
        # Patient 1
        "standby assist",
        # Patient 2
        "gait",
        "fall",
        "falls",
        "person assist",
        r"\dp assist",
        "on feet",
        "unsteady",
        "mobility",
        "up to",
        "walk",
        # Patient 3
        "into bed",
        r"\d ?pa",
        "pivot assist",
        "up in",
        "fell",
    ],
    "Nutrition": [
        "ate",
        "water",
        "swallow",
        "thirsty",
        "eating",
        "drinking",
        "PO",
    ],
    "Toileting": [
        "stool",
        "BM",
        "bm ?x",
        "foley",
        "diarrhea",
        "incontinent",
        "incontinence",
        "incont",
        "urine",
        "bathroom",
        "urinal",
        "bowel",
        "voided",
        "peeing",
        "rectal",
        "catheter",
        "flexiseal",
    ],
    "Behaviour": [
        # Patient 1,
        "pleasant",
        "concerns",
        # Patient 2
        "calm",
        "compliant",
        "alert",
        "refused",
        "wanted",
        "cooperative",
        "drowsy",
        "settled",
        "removing",
        "removes",
        "restless",
        "speech",
        "mumbles",
        "wakes easily",
        "responding",
        "lethargic",
        "restraints",
        "tried to",
        # Patient 3
        "orientated",
        "confusion",
        "confused",
        "crying",
        "slept",
    ]
}
